# Parus customized meta file IO functions

import warnings
import csv
import json
import copy
import numpy as np

"""Function list:
conv_lin_prb(prb_file): Convert linear probe definition file to standard probe data structure.
read_spk_info(spk_info_csv, cell_mode, trim_negat, trim_noise): Import spike timing data form JRClust output.
read_cell_type(cell_type_csv): Read cell type definition CSV file.
"""


def conv_lin_prb(prb_file):
    """ Convert linear probe definition file to standard probe data structure.

    Args:
        prb_file (str): Probe definition file (*.prb)

    Returns:
        list[dict] | None: Probe definition information, structure as follows:
                           list[{'id': int, 'shk': int, 'col': int, 'geo': (float, float), 'pad': (float, float)}]
    """
    # Read in file
    with open(prb_file) as infile:
        try:
            prb_dat = json.load(infile)
        except json.decoder.JSONDecodeError:
            warnings.warn("Invalid probe definition file format.", Warning, 2)
            return None
    # Checking for keys
    miss_key = str()
    for k in ['channel', 'n_chs', 'n_shk', 'n_col', 'gap_chs', 'gap_shk', 'sft_shk', 'gap_col', 'sft_col', 'pad']:
        if k not in prb_dat:
            miss_key += "'" + k + "', "
    if miss_key:
        miss_key = miss_key.rstrip(", ")
        warnings.warn("Key [%s] missing in probe definition file, please verify file integrity." % miss_key, Warning, 2)
        return None

    # Read basic information of the probe sites
    channel = prb_dat['channel']
    n_chs = prb_dat['n_chs']
    n_shk = prb_dat['n_shk']
    n_col = prb_dat['n_col']
    # Read geometry parameters in micrometers
    gap_chs = prb_dat['gap_chs']
    gap_shk = prb_dat['gap_shk']
    sft_shk = prb_dat['sft_shk']
    gap_col = prb_dat['gap_col']
    sft_col = prb_dat['sft_col']
    # Recording contact pad size in micrometers (height X width)
    pad = prb_dat['pad']

    # Compute group definition
    n_grp = int(n_col * n_shk)
    grp_lst = []  # INIT VAR
    for i in range(n_shk):
        for j in range(n_col):
            grp_lst.append((i + 1, j + 1))

    # Arrange probe information
    prb_def = []  # INIT VAR
    ch_dat_temp = {'id': int, 'shk': int, 'col': int, 'geo': (float, float), 'pad': (float, float)}  # INIT VAR
    for i in range(n_chs):
        # Assign basic information
        ch_dat_temp['id'] = channel[i] - 1
        ch_dat_temp['pad'] = (pad[0], pad[1])
        # Compute and assign group information
        grp_idx = i % n_grp
        ch_shk = grp_lst[grp_idx][0]
        ch_col = grp_lst[grp_idx][1]
        ch_dat_temp['shk'] = ch_shk
        ch_dat_temp['col'] = ch_col
        # Compute channel geometric information
        grp_cnt = i // n_grp
        ch_xlc = gap_col * (ch_col - 1) + gap_shk * (ch_shk - 1)
        ch_ylc = gap_chs * grp_cnt + sft_col * (ch_col - 1) + sft_shk * (ch_shk - 1)
        ch_dat_temp['geo'] = (ch_xlc, ch_ylc)
        # Assign to output array
        prb_def.append(copy.deepcopy(ch_dat_temp))

    return prb_def


def read_spk_info(spk_info_csv, cell_mode=True, trim_negat=True, trim_noise=False):
    """ Import spike timing data form JRClust output.

     Args:
          spk_info_csv (str): Cell spike timing CSV file generated by [JRClust]
          cell_mode (bool): Arrange data with cell ID if [True]; arrange with channel ID if [False] (default: True)
          trim_negat (bool): Remove negative (manual deleted cells) IDs if [True] (default: True)
          trim_noise (bool): Remove noise information (cell ID: 0) from output (default: False)

    Returns:
        dict[int, dict[int, np.ndarray]]: Arranged spike timing data, data structure as follows:
                                          CELL: {cell_id: {prob_ch: spk_time}}; CHANNEL: {prob_ch: {cell_id: spk_time}}
    """
    with open(spk_info_csv, "r") as csv_file:
        jrc_data = np.loadtxt(csv_file, delimiter=",")
    spk_data = {}  # INIT VAR
    # Read and arrange data with cell ID
    if cell_mode:
        cell_id = np.unique(jrc_data[:, 1])  # Get unique cell numbers
        for cid in cell_id:
            if (not trim_negat) or (int(cid.item()) >= 0):
                prob_ch = np.unique(jrc_data[:, 2][jrc_data[:, 1] == cid])  # Get probe channels have cell
                spk_temp = {}  # INIT/RESET VAR
                for pch in prob_ch:
                    spk = jrc_data[:, 0][(jrc_data[:, 1] == cid) & (jrc_data[:, 2] == pch)]  # Get spike timings
                    spk_temp[int(pch.item()) - 1] = spk
                spk_data[int(cid.item())] = spk_temp
        if trim_noise:
            spk_data.pop(0, None)
    # Read and arrange data with channel ID
    else:
        prob_ch = np.unique(jrc_data[:, 2])  # Get unique probe channels
        for pch in prob_ch:
            cell_id = np.unique(jrc_data[:, 1][jrc_data[:, 2] == pch])  # Get cell IDs within channel
            spk_temp = {}  # INIT/RESET VAR
            for cid in cell_id:
                if (not trim_negat) or (int(cid.item()) >= 0):
                    spk = jrc_data[:, 0][(jrc_data[:, 2] == pch) & (jrc_data[:, 1] == cid)]  # Get spike timings
                    spk_temp[int(cid.item())] = spk
                if trim_noise:
                    spk_temp.pop(0, None)
            spk_data[int(pch.item()) - 1] = spk_temp
    # Set output
    return spk_data


def read_cell_type(cell_type_csv):
    """ Read cell type definition CSV file.

    Args:
        cell_type_csv (str): Cell type CSV file

    Returns:
        dict[int, str]: Arranged cell type information ({cell_id: cell_type})
    """
    # Read data in CSV file
    with open(cell_type_csv, "r") as csv_file:
        csv_reader = csv.reader(csv_file)
        no = []  # INIT VAR
        tp = []  # INIT VAR
        for row in csv_reader:
            no.append(int(row[0]))
            tp.append(row[1])
    # Initialize output dictionary
    cell_type = {}
    for n in no:
        cell_type[n] = str()
    # Arrange data for output
    for s in set(tp):
        i = 0
        for t in range(len(tp)):
            if tp[t] == s:
                cell_type[no[t]] = tp[t] + "_%03d" % i
                i += 1
    return cell_type
