from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SigScopeWindow(object):
    def setupUi(self, SigScopeWindow):
        SigScopeWindow.setObjectName("SigScopeWindow")
        SigScopeWindow.resize(630, 644)
        self.centralWidget = QtWidgets.QWidget(SigScopeWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.centralLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.centralLayout.setContentsMargins(15, 0, 15, 15)
        self.centralLayout.setObjectName("centralLayout")
        self.signalFrame = QtWidgets.QFrame(self.centralWidget)
        self.signalFrame.setMinimumSize(QtCore.QSize(600, 450))
        self.signalFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.signalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.signalFrame.setObjectName("signalFrame")
        self.signalLayout = QtWidgets.QVBoxLayout(self.signalFrame)
        self.signalLayout.setObjectName("signalLayout")
        self.centralLayout.addWidget(self.signalFrame)
        self.signalSlider = QtWidgets.QSlider(self.centralWidget)
        self.signalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.signalSlider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.signalSlider.setObjectName("signalSlider")
        self.centralLayout.addWidget(self.signalSlider)
        self.controlsLayout = QtWidgets.QHBoxLayout()
        self.controlsLayout.setContentsMargins(6, -1, 6, 6)
        self.controlsLayout.setObjectName("controlsLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.controlsLayout.addItem(spacerItem)
        self.tagsLayout = QtWidgets.QVBoxLayout()
        self.tagsLayout.setObjectName("tagsLayout")
        self.nameLabel = QtWidgets.QLabel(self.centralWidget)
        self.nameLabel.setMinimumSize(QtCore.QSize(100, 16))
        self.nameLabel.setMaximumSize(QtCore.QSize(100, 16))
        self.nameLabel.setObjectName("nameLabel")
        self.tagsLayout.addWidget(self.nameLabel)
        self.nameLine = QtWidgets.QLineEdit(self.centralWidget)
        self.nameLine.setEnabled(False)
        self.nameLine.setMinimumSize(QtCore.QSize(200, 20))
        self.nameLine.setMaximumSize(QtCore.QSize(200, 20))
        self.nameLine.setObjectName("nameLine")
        self.tagsLayout.addWidget(self.nameLine)
        self.probeLabel = QtWidgets.QLabel(self.centralWidget)
        self.probeLabel.setMinimumSize(QtCore.QSize(100, 16))
        self.probeLabel.setMaximumSize(QtCore.QSize(100, 16))
        self.probeLabel.setObjectName("probeLabel")
        self.tagsLayout.addWidget(self.probeLabel)
        self.probeLine = QtWidgets.QLineEdit(self.centralWidget)
        self.probeLine.setEnabled(False)
        self.probeLine.setMinimumSize(QtCore.QSize(200, 20))
        self.probeLine.setMaximumSize(QtCore.QSize(200, 20))
        self.probeLine.setObjectName("probeLine")
        self.tagsLayout.addWidget(self.probeLine)
        self.controlsLayout.addLayout(self.tagsLayout)
        self.infoLayout = QtWidgets.QVBoxLayout()
        self.infoLayout.setObjectName("infoLayout")
        self.systemLabel = QtWidgets.QLabel(self.centralWidget)
        self.systemLabel.setMinimumSize(QtCore.QSize(100, 16))
        self.systemLabel.setMaximumSize(QtCore.QSize(100, 16))
        self.systemLabel.setObjectName("systemLabel")
        self.infoLayout.addWidget(self.systemLabel)
        self.systemLine = QtWidgets.QLineEdit(self.centralWidget)
        self.systemLine.setEnabled(False)
        self.systemLine.setMinimumSize(QtCore.QSize(100, 20))
        self.systemLine.setMaximumSize(QtCore.QSize(100, 20))
        self.systemLine.setObjectName("systemLine")
        self.infoLayout.addWidget(self.systemLine)
        self.countLabel = QtWidgets.QLabel(self.centralWidget)
        self.countLabel.setMinimumSize(QtCore.QSize(100, 16))
        self.countLabel.setMaximumSize(QtCore.QSize(100, 16))
        self.countLabel.setObjectName("countLabel")
        self.infoLayout.addWidget(self.countLabel)
        self.countLine = QtWidgets.QLineEdit(self.centralWidget)
        self.countLine.setEnabled(False)
        self.countLine.setMinimumSize(QtCore.QSize(100, 20))
        self.countLine.setMaximumSize(QtCore.QSize(100, 20))
        self.countLine.setObjectName("countLine")
        self.infoLayout.addWidget(self.countLine)
        self.controlsLayout.addLayout(self.infoLayout)
        self.selectionLayout = QtWidgets.QVBoxLayout()
        self.selectionLayout.setObjectName("selectionLayout")
        self.channelLabel = QtWidgets.QLabel(self.centralWidget)
        self.channelLabel.setMinimumSize(QtCore.QSize(100, 16))
        self.channelLabel.setMaximumSize(QtCore.QSize(100, 16))
        self.channelLabel.setObjectName("channelLabel")
        self.selectionLayout.addWidget(self.channelLabel)
        self.channelBox = QtWidgets.QComboBox(self.centralWidget)
        self.channelBox.setMinimumSize(QtCore.QSize(120, 20))
        self.channelBox.setMaximumSize(QtCore.QSize(120, 20))
        self.channelBox.setObjectName("channelBox")
        self.selectionLayout.addWidget(self.channelBox)
        self.annotationLabel = QtWidgets.QLabel(self.centralWidget)
        self.annotationLabel.setMinimumSize(QtCore.QSize(100, 16))
        self.annotationLabel.setMaximumSize(QtCore.QSize(100, 16))
        self.annotationLabel.setObjectName("annotationLabel")
        self.selectionLayout.addWidget(self.annotationLabel)
        self.annotationBox = QtWidgets.QComboBox(self.centralWidget)
        self.annotationBox.setMinimumSize(QtCore.QSize(120, 20))
        self.annotationBox.setMaximumSize(QtCore.QSize(120, 20))
        self.annotationBox.setObjectName("annotationBox")
        self.selectionLayout.addWidget(self.annotationBox)
        self.controlsLayout.addLayout(self.selectionLayout)
        self.timeLayout = QtWidgets.QVBoxLayout()
        self.timeLayout.setObjectName("timeLayout")
        self.rangeLabel = QtWidgets.QLabel(self.centralWidget)
        self.rangeLabel.setMinimumSize(QtCore.QSize(100, 16))
        self.rangeLabel.setMaximumSize(QtCore.QSize(100, 16))
        self.rangeLabel.setObjectName("rangeLabel")
        self.timeLayout.addWidget(self.rangeLabel)
        self.rangeValue = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.rangeValue.setMinimumSize(QtCore.QSize(120, 20))
        self.rangeValue.setMaximumSize(QtCore.QSize(120, 20))
        self.rangeValue.setSuffix(" ms")
        self.rangeValue.setMinimum(0.5)
        self.rangeValue.setMaximum(10000.0)
        self.rangeValue.setProperty("value", 5000.0)
        self.rangeValue.setObjectName("rangeValue")
        self.timeLayout.addWidget(self.rangeValue)
        self.stepLabel = QtWidgets.QLabel(self.centralWidget)
        self.stepLabel.setMinimumSize(QtCore.QSize(100, 16))
        self.stepLabel.setMaximumSize(QtCore.QSize(100, 16))
        self.stepLabel.setObjectName("stepLabel")
        self.timeLayout.addWidget(self.stepLabel)
        self.stepValue = QtWidgets.QDoubleSpinBox(self.centralWidget)
        self.stepValue.setMinimumSize(QtCore.QSize(120, 20))
        self.stepValue.setMaximumSize(QtCore.QSize(120, 20))
        self.stepValue.setSuffix(" ms")
        self.stepValue.setMinimum(0.1)
        self.stepValue.setMaximum(10000.0)
        self.stepValue.setProperty("value", 2500.0)
        self.stepValue.setObjectName("stepValue")
        self.timeLayout.addWidget(self.stepValue)
        self.controlsLayout.addLayout(self.timeLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.controlsLayout.addItem(spacerItem1)
        self.centralLayout.addLayout(self.controlsLayout)
        SigScopeWindow.setCentralWidget(self.centralWidget)
        self.menubar = QtWidgets.QMenuBar(SigScopeWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 630, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        SigScopeWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SigScopeWindow)
        self.statusbar.setObjectName("statusbar")
        SigScopeWindow.setStatusBar(self.statusbar)
        self.actionLoadIntan = QtWidgets.QAction(SigScopeWindow)
        self.actionLoadIntan.setObjectName("actionLoadIntan")
        self.actionExit = QtWidgets.QAction(SigScopeWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionLoadIntan)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(SigScopeWindow)
        QtCore.QMetaObject.connectSlotsByName(SigScopeWindow)

    def retranslateUi(self, SigScopeWindow):
        _translate = QtCore.QCoreApplication.translate
        SigScopeWindow.setWindowTitle(_translate("SigScopeWindow", "Parus Signal Scope"))
        self.nameLabel.setText(_translate("SigScopeWindow", "Recording ID"))
        self.probeLabel.setText(_translate("SigScopeWindow", "Probe Type"))
        self.systemLabel.setText(_translate("SigScopeWindow", "Recording System"))
        self.countLabel.setText(_translate("SigScopeWindow", "Number of Channels"))
        self.channelLabel.setText(_translate("SigScopeWindow", "Signal Channel"))
        self.annotationLabel.setText(_translate("SigScopeWindow", "Annotated Cell"))
        self.rangeLabel.setText(_translate("SigScopeWindow", "Time Range"))
        self.stepLabel.setText(_translate("SigScopeWindow", "Scroll Step"))
        self.menuFile.setTitle(_translate("SigScopeWindow", "File"))
        self.actionLoadIntan.setText(_translate("SigScopeWindow", "Load Intan Data"))
        self.actionExit.setText(_translate("SigScopeWindow", "Exit"))


class Ui_IntanDataLoaderDialog(object):
    def setupUi(self, IntanDataLoaderDialog):
        IntanDataLoaderDialog.setObjectName("IntanDataLoaderDialog")
        IntanDataLoaderDialog.resize(468, 351)
        IntanDataLoaderDialog.setMinimumSize(QtCore.QSize(468, 351))
        IntanDataLoaderDialog.setMaximumSize(QtCore.QSize(468, 351))
        self.loaderLayout = QtWidgets.QVBoxLayout(IntanDataLoaderDialog)
        self.loaderLayout.setObjectName("loaderLayout")
        self.recordBox = QtWidgets.QGroupBox(IntanDataLoaderDialog)
        self.recordBox.setMinimumSize(QtCore.QSize(450, 120))
        self.recordBox.setMaximumSize(QtCore.QSize(450, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.recordBox.setFont(font)
        self.recordBox.setObjectName("recordBox")
        self.recordLayout = QtWidgets.QVBoxLayout(self.recordBox)
        self.recordLayout.setContentsMargins(-1, 6, -1, 6)
        self.recordLayout.setObjectName("recordLayout")
        self.dataLayout = QtWidgets.QVBoxLayout()
        self.dataLayout.setSpacing(3)
        self.dataLayout.setObjectName("dataLayout")
        self.dataLabel = QtWidgets.QLabel(self.recordBox)
        self.dataLabel.setMinimumSize(QtCore.QSize(200, 16))
        self.dataLabel.setMaximumSize(QtCore.QSize(200, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dataLabel.setFont(font)
        self.dataLabel.setObjectName("dataLabel")
        self.dataLayout.addWidget(self.dataLabel)
        self.dataPathLayout = QtWidgets.QHBoxLayout()
        self.dataPathLayout.setSpacing(0)
        self.dataPathLayout.setObjectName("dataPathLayout")
        self.dataPath = QtWidgets.QLineEdit(self.recordBox)
        self.dataPath.setMinimumSize(QtCore.QSize(400, 20))
        self.dataPath.setMaximumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dataPath.setFont(font)
        self.dataPath.setObjectName("dataPath")
        self.dataPathLayout.addWidget(self.dataPath)
        self.dataButton = QtWidgets.QToolButton(self.recordBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.dataButton.setFont(font)
        self.dataButton.setText("...")
        self.dataButton.setObjectName("dataButton")
        self.dataPathLayout.addWidget(self.dataButton)
        self.dataLayout.addLayout(self.dataPathLayout)
        self.recordLayout.addLayout(self.dataLayout)
        self.infoLayout = QtWidgets.QHBoxLayout()
        self.infoLayout.setObjectName("infoLayout")
        self.portLayout = QtWidgets.QVBoxLayout()
        self.portLayout.setSpacing(3)
        self.portLayout.setObjectName("portLayout")
        self.portLabel = QtWidgets.QLabel(self.recordBox)
        self.portLabel.setMinimumSize(QtCore.QSize(30, 16))
        self.portLabel.setMaximumSize(QtCore.QSize(30, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.portLabel.setFont(font)
        self.portLabel.setObjectName("portLabel")
        self.portLayout.addWidget(self.portLabel)
        self.portTag = QtWidgets.QComboBox(self.recordBox)
        self.portTag.setMinimumSize(QtCore.QSize(30, 20))
        self.portTag.setMaximumSize(QtCore.QSize(30, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.portTag.setFont(font)
        self.portTag.setObjectName("portTag")
        self.portTag.addItem("")
        self.portTag.setItemText(0, "A")
        self.portTag.addItem("")
        self.portTag.setItemText(1, "B")
        self.portTag.addItem("")
        self.portTag.setItemText(2, "C")
        self.portTag.addItem("")
        self.portTag.setItemText(3, "D")
        self.portLayout.addWidget(self.portTag)
        self.infoLayout.addLayout(self.portLayout)
        spacerItem = QtWidgets.QSpacerItem(13, 35, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.infoLayout.addItem(spacerItem)
        self.channelsLayout = QtWidgets.QVBoxLayout()
        self.channelsLayout.setSpacing(3)
        self.channelsLayout.setObjectName("channelsLayout")
        self.channelLabel = QtWidgets.QLabel(self.recordBox)
        self.channelLabel.setMinimumSize(QtCore.QSize(75, 16))
        self.channelLabel.setMaximumSize(QtCore.QSize(75, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.channelLabel.setFont(font)
        self.channelLabel.setObjectName("channelLabel")
        self.channelsLayout.addWidget(self.channelLabel)
        self.channelValue = QtWidgets.QSpinBox(self.recordBox)
        self.channelValue.setMinimumSize(QtCore.QSize(75, 20))
        self.channelValue.setMaximumSize(QtCore.QSize(75, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.channelValue.setFont(font)
        self.channelValue.setMaximum(10240)
        self.channelValue.setProperty("value", 32)
        self.channelValue.setObjectName("channelValue")
        self.channelsLayout.addWidget(self.channelValue)
        self.infoLayout.addLayout(self.channelsLayout)
        spacerItem1 = QtWidgets.QSpacerItem(13, 35, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.infoLayout.addItem(spacerItem1)
        self.frequencyLayout = QtWidgets.QVBoxLayout()
        self.frequencyLayout.setSpacing(3)
        self.frequencyLayout.setObjectName("frequencyLayout")
        self.frequencyLabel = QtWidgets.QLabel(self.recordBox)
        self.frequencyLabel.setMinimumSize(QtCore.QSize(100, 16))
        self.frequencyLabel.setMaximumSize(QtCore.QSize(100, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frequencyLabel.setFont(font)
        self.frequencyLabel.setObjectName("frequencyLabel")
        self.frequencyLayout.addWidget(self.frequencyLabel)
        self.frequencyValue = QtWidgets.QSpinBox(self.recordBox)
        self.frequencyValue.setMinimumSize(QtCore.QSize(100, 20))
        self.frequencyValue.setMaximumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frequencyValue.setFont(font)
        self.frequencyValue.setSuffix(" Hz")
        self.frequencyValue.setMaximum(100000)
        self.frequencyValue.setProperty("value", 20000)
        self.frequencyValue.setObjectName("frequencyValue")
        self.frequencyLayout.addWidget(self.frequencyValue)
        self.infoLayout.addLayout(self.frequencyLayout)
        self.recordLayout.addLayout(self.infoLayout)
        self.loaderLayout.addWidget(self.recordBox)
        self.probeBox = QtWidgets.QGroupBox(IntanDataLoaderDialog)
        self.probeBox.setMinimumSize(QtCore.QSize(450, 50))
        self.probeBox.setMaximumSize(QtCore.QSize(450, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.probeBox.setFont(font)
        self.probeBox.setObjectName("probeBox")
        self.probeLayout = QtWidgets.QHBoxLayout(self.probeBox)
        self.probeLayout.setContentsMargins(-1, 6, -1, 6)
        self.probeLayout.setSpacing(0)
        self.probeLayout.setObjectName("probeLayout")
        self.probePath = QtWidgets.QLineEdit(self.probeBox)
        self.probePath.setMinimumSize(QtCore.QSize(400, 20))
        self.probePath.setMaximumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.probePath.setFont(font)
        self.probePath.setObjectName("probePath")
        self.probeLayout.addWidget(self.probePath)
        self.probeButton = QtWidgets.QToolButton(self.probeBox)
        self.probeButton.setMinimumSize(QtCore.QSize(0, 20))
        self.probeButton.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.probeButton.setFont(font)
        self.probeButton.setText("...")
        self.probeButton.setObjectName("probeButton")
        self.probeLayout.addWidget(self.probeButton)
        self.loaderLayout.addWidget(self.probeBox)
        self.annotationBox = QtWidgets.QGroupBox(IntanDataLoaderDialog)
        self.annotationBox.setMinimumSize(QtCore.QSize(450, 120))
        self.annotationBox.setMaximumSize(QtCore.QSize(450, 120))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.annotationBox.setFont(font)
        self.annotationBox.setObjectName("annotationBox")
        self.annotationLayout = QtWidgets.QVBoxLayout(self.annotationBox)
        self.annotationLayout.setContentsMargins(-1, 6, -1, 6)
        self.annotationLayout.setObjectName("annotationLayout")
        self.spikeLayout = QtWidgets.QVBoxLayout()
        self.spikeLayout.setSpacing(3)
        self.spikeLayout.setObjectName("spikeLayout")
        self.spikeLabel = QtWidgets.QLabel(self.annotationBox)
        self.spikeLabel.setMinimumSize(QtCore.QSize(200, 16))
        self.spikeLabel.setMaximumSize(QtCore.QSize(200, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spikeLabel.setFont(font)
        self.spikeLabel.setObjectName("spikeLabel")
        self.spikeLayout.addWidget(self.spikeLabel)
        self.spikePathLayout = QtWidgets.QHBoxLayout()
        self.spikePathLayout.setSpacing(0)
        self.spikePathLayout.setObjectName("spikePathLayout")
        self.spikePath = QtWidgets.QLineEdit(self.annotationBox)
        self.spikePath.setMinimumSize(QtCore.QSize(400, 20))
        self.spikePath.setMaximumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spikePath.setFont(font)
        self.spikePath.setObjectName("spikePath")
        self.spikePathLayout.addWidget(self.spikePath)
        self.spikeButton = QtWidgets.QToolButton(self.annotationBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.spikeButton.setFont(font)
        self.spikeButton.setText("...")
        self.spikeButton.setObjectName("spikeButton")
        self.spikePathLayout.addWidget(self.spikeButton)
        self.spikeLayout.addLayout(self.spikePathLayout)
        self.annotationLayout.addLayout(self.spikeLayout)
        self.typeLayout = QtWidgets.QVBoxLayout()
        self.typeLayout.setSpacing(3)
        self.typeLayout.setObjectName("typeLayout")
        self.typeLabel = QtWidgets.QLabel(self.annotationBox)
        self.typeLabel.setMinimumSize(QtCore.QSize(200, 16))
        self.typeLabel.setMaximumSize(QtCore.QSize(200, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.typeLabel.setFont(font)
        self.typeLabel.setObjectName("typeLabel")
        self.typeLayout.addWidget(self.typeLabel)
        self.typePathLayout = QtWidgets.QHBoxLayout()
        self.typePathLayout.setSpacing(0)
        self.typePathLayout.setObjectName("typePathLayout")
        self.typePath = QtWidgets.QLineEdit(self.annotationBox)
        self.typePath.setMinimumSize(QtCore.QSize(400, 20))
        self.typePath.setMaximumSize(QtCore.QSize(400, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.typePath.setFont(font)
        self.typePath.setObjectName("typePath")
        self.typePathLayout.addWidget(self.typePath)
        self.typeButton = QtWidgets.QToolButton(self.annotationBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.typeButton.setFont(font)
        self.typeButton.setText("...")
        self.typeButton.setObjectName("typeButton")
        self.typePathLayout.addWidget(self.typeButton)
        self.typeLayout.addLayout(self.typePathLayout)
        self.annotationLayout.addLayout(self.typeLayout)
        self.loaderLayout.addWidget(self.annotationBox)
        self.controlsLayout = QtWidgets.QHBoxLayout()
        self.controlsLayout.setObjectName("controlsLayout")
        self.cancelButton = QtWidgets.QPushButton(IntanDataLoaderDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(75, 23))
        self.cancelButton.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.controlsLayout.addWidget(self.cancelButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.controlsLayout.addItem(spacerItem2)
        self.loadButton = QtWidgets.QPushButton(IntanDataLoaderDialog)
        self.loadButton.setMinimumSize(QtCore.QSize(75, 23))
        self.loadButton.setMaximumSize(QtCore.QSize(75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.loadButton.setFont(font)
        self.loadButton.setDefault(True)
        self.loadButton.setObjectName("loadButton")
        self.controlsLayout.addWidget(self.loadButton)
        self.loaderLayout.addLayout(self.controlsLayout)

        self.retranslateUi(IntanDataLoaderDialog)
        QtCore.QMetaObject.connectSlotsByName(IntanDataLoaderDialog)
        IntanDataLoaderDialog.setTabOrder(self.dataPath, self.dataButton)
        IntanDataLoaderDialog.setTabOrder(self.dataButton, self.portTag)
        IntanDataLoaderDialog.setTabOrder(self.portTag, self.channelValue)
        IntanDataLoaderDialog.setTabOrder(self.channelValue, self.frequencyValue)
        IntanDataLoaderDialog.setTabOrder(self.frequencyValue, self.probePath)
        IntanDataLoaderDialog.setTabOrder(self.probePath, self.probeButton)
        IntanDataLoaderDialog.setTabOrder(self.probeButton, self.spikePath)
        IntanDataLoaderDialog.setTabOrder(self.spikePath, self.spikeButton)
        IntanDataLoaderDialog.setTabOrder(self.spikeButton, self.typePath)
        IntanDataLoaderDialog.setTabOrder(self.typePath, self.typeButton)
        IntanDataLoaderDialog.setTabOrder(self.typeButton, self.cancelButton)
        IntanDataLoaderDialog.setTabOrder(self.cancelButton, self.loadButton)

    def retranslateUi(self, IntanDataLoaderDialog):
        _translate = QtCore.QCoreApplication.translate
        IntanDataLoaderDialog.setWindowTitle(_translate("IntanDataLoaderDialog", "Intan Data Loader"))
        self.recordBox.setTitle(_translate("IntanDataLoaderDialog", "Recording Information"))
        self.dataLabel.setText(_translate("IntanDataLoaderDialog", "Data Directory"))
        self.portLabel.setText(_translate("IntanDataLoaderDialog", "Port"))
        self.channelLabel.setText(_translate("IntanDataLoaderDialog", "# of Channels"))
        self.frequencyLabel.setText(_translate("IntanDataLoaderDialog", "Sampling Frequency"))
        self.probeBox.setTitle(_translate("IntanDataLoaderDialog", "Probe Information"))
        self.annotationBox.setTitle(_translate("IntanDataLoaderDialog", "Annotation Information"))
        self.spikeLabel.setText(_translate("IntanDataLoaderDialog", "Cell Spiking Timing Data"))
        self.typeLabel.setText(_translate("IntanDataLoaderDialog", "Cell Type Definition"))
        self.cancelButton.setText(_translate("IntanDataLoaderDialog", "Cancel"))
        self.loadButton.setText(_translate("IntanDataLoaderDialog", "Load"))
